### ISSUE TITLE
Response 7:::1+0

### ISSUE THREAD

**Issue by rockerBOO** [Hitakashi/Hitbox-Chat-Doc#2]
I am not sure what this response means. I am getting it on connection, but I don't know what to do with it. Does it mean my authentication failed?

Thanks for the great documentation!

**Comment by Hitakashi** [comment]
Did a bit of testing, The only way I'm getting 7:::1+0 is if I'm using a bad connection ID. I tried incorrect authentication and the server just drops the message. There's no response on that.

I don't think I specifically said in the doc, but the connection IDs should never be reused.

**Comment by rockerBOO** [comment]
What is a connection id?

**Comment by Hitakashi** [comment]
https://github.com/Hitakashi/Hitbox-Chat-Doc/blob/master/connection.md#websocket-id-step-2

Basically:
1. Get A Server Address from the API
2. Append /socket.io/1/ and do a HTTP GET on that. Get all text before the first colon. That's your connection ID
3. Start a websocket connection with the URL as ws://<url>/socket.io/1/websocket/<connectionId>

**Comment by rockerBOO** [comment]
Oh ok cool, I was re-using it because I thought it would last. Thanks

**Comment by Hitakashi** [comment]
Yup, One time id. Even if you fail to connect it seems to take use that ID. (Ex: You connect but drop before doing anything)
