### ISSUE TITLE
Always receiving 7:::1+0 after connection

### ISSUE THREAD

**Issue by rylat** [Hitakashi/Hitbox-Chat-Doc#3]
After reading #2 I know that there is a problem with the websocket id but it's kind of weird because the bot always pulls a new server address, then new websocket id and then connects to the server but the connection is always closed because of 7:::1+0.

``[DBG] ec2-54-234-172-234.ch.hitbox.tv/socket.io/1/ body: 3TJD_uhIzaFQ3VN5S0id:60:60:websocket
[DBG] Websocket ID: 3TJD_uhIzaFQ3VN5S0id
[DBG] Full address: ws://ec2-54-234-172-234.ch.hitbox.tv/socket.io/1/websocket/3TJD_uhIzaFQ3VN5S0id``

Then 7:::1+0 comes and connection is closed.

**Comment by ghost** [comment]
Turns out websocket id cannot be downloaded when making a request by https (e.g. https://ec2-54-234-172-234.ch.hitbox.tv/socket.io/1/). Changing to HTTP worked.

**Comment by Hitakashi** [comment]
> Full address: ws://ec2-54-234-172-234.ch.hitbox.tv/socket.io/1/websocket/3TJD_uhIzaFQ3VN5S0id

> Turns out websocket id cannot be downloaded when making a request by https

You're grabbing a connection id from https, and then using it on ws. Try using wss.
